// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    Wordlemple: typeof import('./src/components/Wordlemple.vue')['default']
    WordlempleRow: typeof import('./src/components/WordlempleRow.vue')['default']
    WordlempleRowInput: typeof import('./src/components/WordlempleRowInput.vue')['default']
  }
}

export {}
